Add custom_doctor_rst_whitelist_part for ecommerce
sonata-project/dev-kit pull request #893
Opened 2020-09-02 16:04 UTC by wbloszyk

2020-09-02 16:06 UTC, OskarStark requested changes
Please fix indentation error

2020-09-02 21:54 UTC, jordisala1991 approved these changes

2020-09-03 05:25 UTC, OskarStark approved these changes

2020-09-03 05:26 UTC, OskarStark commented
Thank you

2020-09-03 05:26 UTC, merged